name: sync fork

on:
  schedule:
    - cron: '0 0 * * 0' # every sunday at 00:00
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: anatawa12/fork-sync-all-branches@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          exclude: main # well our main is ahead so
